pipeline{
    agent any

    tools {
         maven 'maven'
         jdk 'JDK_17'
    }

    stages{
        stage('checkout'){
            steps{
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'github access', url: 'https://github.com/raghu-1910/Docker_Spring_Project.git']]])
            }
        }
        stage('build'){
            steps{
               bat 'mvn package'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    bat 'wsl docker build -t raghu644/docker-jenkins-integration-sample .'
                }
            }
        }
        stage('Run Container') {
            steps {
                script {
                    bat 'wsl docker run -d -p 8080:8080 --name my-container raghu644/docker-jenkins-integration-sample'
                }
            }
        }
        
}
    }
   
